### ISSUE TITLE
Passing port as string fails

### ISSUE THREAD

**Issue by madshargreave** [jschniper/gelf_logger#11]
Hi

If you're using releases and want to pass in the port as an ENV variable, you'll likely be using the `REPLACE_OS_VARS` approach

```
config :logger, :gelf_logger,
  host: "${GRAYLOG_HOST}",
  port: "${GRAYLOG_PORT}"
```

Problem with that is that the port gets interpreted as a string, which fails when calling the `gen_udp` module.

It'd be nice if the library could handle casting the port to an integer before being used

**Comment by jschniper** [comment]
I've released a new version that converts a binary into an integer when appropriate. I'll publish it to hex in just a minute. Let me know if this solves your problem.

**Comment by madshargreave** [comment]
That was quick! It's perfect, thanks
